# Generated by Django 4.0.3 on 2022-03-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitob',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
