# Generated by Django 4.0.3 on 2022-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpage', '0002_delete_kitob_delete_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='DocFile'),
        ),
        migrations.AlterField(
            model_name='document',
            name='img',
            field=models.ImageField(upload_to='document'),
        ),
    ]
