# Generated by Django 4.0.3 on 2022-03-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workpage', '0004_alter_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='sort',
        ),
    ]
